version: "3.9"
services:
   backend:
    build: ./backend
    ports:
    - "80:5000"
    volumes: 
    - ./backend:/app
    environment:
      FLASK_ENV: development

   frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src/app
    depends_on:
      - backend
